name: Build Release

on:
  release:
    types:
      - published
  push:
    branches:
      - ghactions

permissions:
  contents: read

jobs:
  build-release:
    name: Build and push a tag image
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      with:
        persist-credentials: false

    - uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6.5.0
      with:
        cache: false
        go-version-file: go.mod
      id: go
    - name: Set Env Tags
      run: |
        {
          echo "RELEASE_TAG=$(echo "${GITHUB_REF}" | cut -d '/' -f 3)"
          echo "IMAGE_REGISTRY=$(echo "${_IMAGE_REGISTRY}" | cut -d '/' -f 1)"
          echo "IMAGE_REPO=$(echo "${_IMAGE_REGISTRY}" | cut -d '/' -f 2)"
        } >> "${GITHUB_ENV}"
      env:
        _IMAGE_REGISTRY: ${{ secrets.IMAGE_REGISTRY }}

    - name: Build Operator Image
      id: build-operator-image
      uses: redhat-actions/buildah-build@7a95fa7ee0f02d552a32753e7414641a04307056 # v2.13
      with:
        image: ${{ secrets.IMAGE_REGISTRY }}/operator-certification-operator
        tags: ${{ env.RELEASE_TAG }}
        build-args: |
          release_tag=${{ env.RELEASE_TAG }}
        dockerfiles: |
          ./Dockerfile

    - name: Push Operator Image
      id: push-operator-image
      uses: redhat-actions/push-to-registry@5ed88d269cf581ea9ef6dd6806d01562096bee9c # v2.8
      with:
        image: operator-certification-operator
        tags: ${{ steps.build-operator-image.outputs.tags }}
        registry: ${{ secrets.IMAGE_REGISTRY }}
        username: ${{ secrets.REGISTRY_USER }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    
    - name: Build Bundle
      id: build-bundle
      run: |
        VERSION="${RELEASE_TAG}" \
        USE_IMAGE_DIGESTS="true" \
        make bundle

    # This is a very naive implementation. Mainly for PoC
    - name: Add OpenShift metadata to bundle
      id: add-openshift-metadata
      run: |
        echo '  com.redhat.openshift.versions: "v4.8"' >> bundle/annotations.yaml
        echo 'LABEL com.redhat.openshift.versions="v4.8"' >> bundle.Dockerfile

    - name: Build Bundle Image
      id: build-bundle-image
      uses: redhat-actions/buildah-build@7a95fa7ee0f02d552a32753e7414641a04307056 # v2.13
      with:
        image: ${{ env.IMAGE_REGISTRY }}/${{ env.IMAGE_REPO }}/operator-certification-operator-bundle
        tags: ${{ env.RELEASE_TAG }}
        dockerfiles: |
          ./bundle.Dockerfile

    - name: Push Bundle Image
      id: push-bundle-image
      uses: redhat-actions/push-to-registry@5ed88d269cf581ea9ef6dd6806d01562096bee9c # v2.8
      with:
        image: operator-certification-operator-bundle
        tags: ${{ steps.build-bundle-image.outputs.tags }}
        registry: ${{ env.IMAGE_REGISTRY }}/${{  env.IMAGE_REPO }}
        username: ${{ secrets.REGISTRY_USER }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - run: |
        echo "Operator Image pushed to ${OPERATOR_IMAGE_REGISTRY_PATHS}"
        echo "Bundle Image pushed to ${BUNDLE_IMAGE_REGISTRY_PATHS}"
      env:
        OPERATOR_IMAGE_REGISTRY_PATHS: ${{ steps.push-operator-image.outputs.registry-paths }}
        BUNDLE_IMAGE_REGISTRY_PATHS: ${{ steps.push-bundle-image.outputs.registry-paths }}
