name: Build Main

on:
  push:
    branches: [ main, ghactions ]

permissions:
  contents: read

jobs:
  build-main:
    name: Build and push a main snapshot image
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      with:
        persist-credentials: false
    
    - uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
      with:
        cache: false
        go-version-file: go.mod
      id: go

    - name: Set release version
      run: |
        RELEASE_TAG=$(gh --repo "${GITHUB_REPOSITORY}" release list \
                         --json name,isLatest \
                         --jq '.[] | select(.isLatest) | .name')
        if [ -z "${RELEASE_TAG}" ]; then
          RELEASE_TAG="0.0.0"
        fi
        echo "RELEASE_TAG=${RELEASE_TAG}" | tee -a "${GITHUB_ENV}"
      env:
        GH_TOKEN: ${{ github.token }}

    - name: Set image registry env
      run: |
        echo "IMAGE_REGISTRY=$(echo "${_IMAGE_REGISTRY}" | cut -d '/' -f 1)" >> "${GITHUB_ENV}"
        echo "IMAGE_REPO=$(echo "${_IMAGE_REGISTRY}" | cut -d '/' -f 2)" >> "${GITHUB_ENV}"
      env:
        _IMAGE_REGISTRY: ${{ secrets.IMAGE_REGISTRY }}

    - name: Build Operator Image
      id: build-operator-image
      uses: redhat-actions/buildah-build@719e3c40d8af9790c23eca13f7daa339f2867034 # v3.1.0
      with:
        image: operator-certification-operator
        tags: ${{ github.sha }} latest
        build-args: |
          quay_expiration=1w
          release_tag=${{ env.RELEASE_TAG }}
        dockerfiles: |
          ./Dockerfile

    - name: Push Operator Image
      id: push-operator-image
      uses: redhat-actions/push-to-registry@94ade333c38ecc0e60e94785125d9a52ca423b37 # v3.0.0
      with:
        image: operator-certification-operator
        tags: ${{ steps.build-operator-image.outputs.tags }}
        registry: ${{ env.IMAGE_REGISTRY }}/${{ env.IMAGE_REPO }}
        username: ${{ secrets.REGISTRY_USER }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - name: Build Bundle
      id: build-bundle
      run: |
        VERSION="${RELEASE_TAG}" \
        make bundle

    - name: Build Bundle Image
      id: build-bundle-image
      uses: redhat-actions/buildah-build@719e3c40d8af9790c23eca13f7daa339f2867034 # v3.1.0
      with:
        image: operator-certification-operator-bundle
        tags: latest
        dockerfiles: |
          ./bundle.Dockerfile

    - name: Push Bundle Image
      id: push-bundle-image
      uses: redhat-actions/push-to-registry@94ade333c38ecc0e60e94785125d9a52ca423b37 # v3.0.0
      with:
        image: operator-certification-operator-bundle
        tags: ${{ steps.build-bundle-image.outputs.tags }}
        registry: ${{ env.IMAGE_REGISTRY }}/${{ env.IMAGE_REPO }}
        username: ${{ secrets.REGISTRY_USER }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - run: |
        echo "Operator Image pushed to ${OPERATOR_IMAGE_REGISTRY_PATHS}"
        echo "Bundle Image pushed to ${BUNDLE_IMAGE_REGISTRY_PATHS}"
      env:
        OPERATOR_IMAGE_REGISTRY_PATHS: ${{ steps.push-operator-image.outputs.registry-paths }}
        BUNDLE_IMAGE_REGISTRY_PATHS: ${{ steps.push-bundle-image.outputs.registry-paths }}
